// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/paginator.proto

package ormpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchMode int32

const (
	SearchMode_SEARCH_MODE_UNSPECIFIED       SearchMode = 0
	SearchMode_SEARCH_MODE_CONTAINS          SearchMode = 1
	SearchMode_SEARCH_MODE_PREFIX            SearchMode = 2
	SearchMode_SEARCH_MODE_FULL_TEXT         SearchMode = 3
	SearchMode_SEARCH_MODE_TRIGRAM           SearchMode = 4
	SearchMode_SEARCH_MODE_FULL_TEXT_TRIGRAM SearchMode = 5
)

// Enum value maps for SearchMode.
var (
	SearchMode_name = map[int32]string{
		0: "SEARCH_MODE_UNSPECIFIED",
		1: "SEARCH_MODE_CONTAINS",
		2: "SEARCH_MODE_PREFIX",
		3: "SEARCH_MODE_FULL_TEXT",
		4: "SEARCH_MODE_TRIGRAM",
		5: "SEARCH_MODE_FULL_TEXT_TRIGRAM",
	}
	SearchMode_value = map[string]int32{
		"SEARCH_MODE_UNSPECIFIED":       0,
		"SEARCH_MODE_CONTAINS":          1,
		"SEARCH_MODE_PREFIX":            2,
		"SEARCH_MODE_FULL_TEXT":         3,
		"SEARCH_MODE_TRIGRAM":           4,
		"SEARCH_MODE_FULL_TEXT_TRIGRAM": 5,
	}
)

func (x SearchMode) Enum() *SearchMode {
	p := new(SearchMode)
	*p = x
	return p
}

func (x SearchMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_paginator_proto_enumTypes[0].Descriptor()
}

func (SearchMode) Type() protoreflect.EnumType {
	return &file_proto_paginator_proto_enumTypes[0]
}

func (x SearchMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchMode.Descriptor instead.
func (SearchMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_paginator_proto_rawDescGZIP(), []int{0}
}

type FilterOperator int32

const (
	FilterOperator_FILTER_OPERATOR_UNSPECIFIED        FilterOperator = 0
	FilterOperator_FILTER_OPERATOR_EQUAL              FilterOperator = 1
	FilterOperator_FILTER_OPERATOR_NOT_EQUAL          FilterOperator = 2
	FilterOperator_FILTER_OPERATOR_GREATER_THAN       FilterOperator = 3
	FilterOperator_FILTER_OPERATOR_GREATER_THAN_EQUAL FilterOperator = 4
	FilterOperator_FILTER_OPERATOR_LESS_THAN          FilterOperator = 5
	FilterOperator_FILTER_OPERATOR_LESS_THAN_EQUAL    FilterOperator = 6
	FilterOperator_FILTER_OPERATOR_LIKE               FilterOperator = 7
	FilterOperator_FILTER_OPERATOR_NOT_LIKE           FilterOperator = 8
)

// Enum value maps for FilterOperator.
var (
	FilterOperator_name = map[int32]string{
		0: "FILTER_OPERATOR_UNSPECIFIED",
		1: "FILTER_OPERATOR_EQUAL",
		2: "FILTER_OPERATOR_NOT_EQUAL",
		3: "FILTER_OPERATOR_GREATER_THAN",
		4: "FILTER_OPERATOR_GREATER_THAN_EQUAL",
		5: "FILTER_OPERATOR_LESS_THAN",
		6: "FILTER_OPERATOR_LESS_THAN_EQUAL",
		7: "FILTER_OPERATOR_LIKE",
		8: "FILTER_OPERATOR_NOT_LIKE",
	}
	FilterOperator_value = map[string]int32{
		"FILTER_OPERATOR_UNSPECIFIED":        0,
		"FILTER_OPERATOR_EQUAL":              1,
		"FILTER_OPERATOR_NOT_EQUAL":          2,
		"FILTER_OPERATOR_GREATER_THAN":       3,
		"FILTER_OPERATOR_GREATER_THAN_EQUAL": 4,
		"FILTER_OPERATOR_LESS_THAN":          5,
		"FILTER_OPERATOR_LESS_THAN_EQUAL":    6,
		"FILTER_OPERATOR_LIKE":               7,
		"FILTER_OPERATOR_NOT_LIKE":           8,
	}
)

func (x FilterOperator) Enum() *FilterOperator {
	p := new(FilterOperator)
	*p = x
	return p
}

func (x FilterOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_paginator_proto_enumTypes[1].Descriptor()
}

func (FilterOperator) Type() protoreflect.EnumType {
	return &file_proto_paginator_proto_enumTypes[1]
}

func (x FilterOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterOperator.Descriptor instead.
func (FilterOperator) EnumDescriptor() ([]byte, []int) {
	return file_proto_paginator_proto_rawDescGZIP(), []int{1}
}

type QueryOptions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Page           uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit          uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Select         []string               `protobuf:"bytes,3,rep,name=select,proto3" json:"select,omitempty"`
	Sort           []*SortField           `protobuf:"bytes,4,rep,name=sort,proto3" json:"sort,omitempty"`
	Search         *SearchQuery           `protobuf:"bytes,5,opt,name=search,proto3" json:"search,omitempty"`
	SearchAnd      *SearchQueryAnd        `protobuf:"bytes,6,opt,name=search_and,json=searchAnd,proto3" json:"search_and,omitempty"`
	Filters        []*Filter              `protobuf:"bytes,7,rep,name=filters,proto3" json:"filters,omitempty"`
	InMemoryOffset *InMemoryOffsetOptions `protobuf:"bytes,8,opt,name=in_memory_offset,json=inMemoryOffset,proto3" json:"in_memory_offset,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryOptions) Reset() {
	*x = QueryOptions{}
	mi := &file_proto_paginator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOptions) ProtoMessage() {}

func (x *QueryOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paginator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOptions.ProtoReflect.Descriptor instead.
func (*QueryOptions) Descriptor() ([]byte, []int) {
	return file_proto_paginator_proto_rawDescGZIP(), []int{0}
}

func (x *QueryOptions) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *QueryOptions) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryOptions) GetSelect() []string {
	if x != nil {
		return x.Select
	}
	return nil
}

func (x *QueryOptions) GetSort() []*SortField {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *QueryOptions) GetSearch() *SearchQuery {
	if x != nil {
		return x.Search
	}
	return nil
}

func (x *QueryOptions) GetSearchAnd() *SearchQueryAnd {
	if x != nil {
		return x.SearchAnd
	}
	return nil
}

func (x *QueryOptions) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *QueryOptions) GetInMemoryOffset() *InMemoryOffsetOptions {
	if x != nil {
		return x.InMemoryOffset
	}
	return nil
}

type SortField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Desc          bool                   `protobuf:"varint,2,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortField) Reset() {
	*x = SortField{}
	mi := &file_proto_paginator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortField) ProtoMessage() {}

func (x *SortField) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paginator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortField.ProtoReflect.Descriptor instead.
func (*SortField) Descriptor() ([]byte, []int) {
	return file_proto_paginator_proto_rawDescGZIP(), []int{1}
}

func (x *SortField) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *SortField) GetDesc() bool {
	if x != nil {
		return x.Desc
	}
	return false
}

type SearchQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []string               `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Mode          SearchMode             `protobuf:"varint,3,opt,name=mode,proto3,enum=orm.v1.SearchMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchQuery) Reset() {
	*x = SearchQuery{}
	mi := &file_proto_paginator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchQuery) ProtoMessage() {}

func (x *SearchQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paginator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchQuery.ProtoReflect.Descriptor instead.
func (*SearchQuery) Descriptor() ([]byte, []int) {
	return file_proto_paginator_proto_rawDescGZIP(), []int{2}
}

func (x *SearchQuery) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *SearchQuery) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchQuery) GetMode() SearchMode {
	if x != nil {
		return x.Mode
	}
	return SearchMode_SEARCH_MODE_UNSPECIFIED
}

type InMemoryOffsetOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        *Cursor                `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	MaxLimit      uint32                 `protobuf:"varint,2,opt,name=max_limit,json=maxLimit,proto3" json:"max_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InMemoryOffsetOptions) Reset() {
	*x = InMemoryOffsetOptions{}
	mi := &file_proto_paginator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InMemoryOffsetOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InMemoryOffsetOptions) ProtoMessage() {}

func (x *InMemoryOffsetOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paginator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InMemoryOffsetOptions.ProtoReflect.Descriptor instead.
func (*InMemoryOffsetOptions) Descriptor() ([]byte, []int) {
	return file_proto_paginator_proto_rawDescGZIP(), []int{3}
}

func (x *InMemoryOffsetOptions) GetCursor() *Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *InMemoryOffsetOptions) GetMaxLimit() uint32 {
	if x != nil {
		return x.MaxLimit
	}
	return 0
}

type Cursor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cursor) Reset() {
	*x = Cursor{}
	mi := &file_proto_paginator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cursor) ProtoMessage() {}

func (x *Cursor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paginator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cursor.ProtoReflect.Descriptor instead.
func (*Cursor) Descriptor() ([]byte, []int) {
	return file_proto_paginator_proto_rawDescGZIP(), []int{4}
}

func (x *Cursor) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Cursor) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SearchField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchField) Reset() {
	*x = SearchField{}
	mi := &file_proto_paginator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchField) ProtoMessage() {}

func (x *SearchField) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paginator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchField.ProtoReflect.Descriptor instead.
func (*SearchField) Descriptor() ([]byte, []int) {
	return file_proto_paginator_proto_rawDescGZIP(), []int{5}
}

func (x *SearchField) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *SearchField) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type SearchQueryAnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*SearchField         `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchQueryAnd) Reset() {
	*x = SearchQueryAnd{}
	mi := &file_proto_paginator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchQueryAnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchQueryAnd) ProtoMessage() {}

func (x *SearchQueryAnd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paginator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchQueryAnd.ProtoReflect.Descriptor instead.
func (*SearchQueryAnd) Descriptor() ([]byte, []int) {
	return file_proto_paginator_proto_rawDescGZIP(), []int{6}
}

func (x *SearchQueryAnd) GetFields() []*SearchField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Operator      FilterOperator         `protobuf:"varint,2,opt,name=operator,proto3,enum=orm.v1.FilterOperator" json:"operator,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Values        []string               `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_proto_paginator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paginator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_proto_paginator_proto_rawDescGZIP(), []int{7}
}

func (x *Filter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Filter) GetOperator() FilterOperator {
	if x != nil {
		return x.Operator
	}
	return FilterOperator_FILTER_OPERATOR_UNSPECIFIED
}

func (x *Filter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Filter) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type QueryPageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	TotalPages    uint32                 `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	HasNext       bool                   `protobuf:"varint,5,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	HasPrev       bool                   `protobuf:"varint,6,opt,name=has_prev,json=hasPrev,proto3" json:"has_prev,omitempty"`
	NextCursor    string                 `protobuf:"bytes,7,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPageResponse) Reset() {
	*x = QueryPageResponse{}
	mi := &file_proto_paginator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPageResponse) ProtoMessage() {}

func (x *QueryPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paginator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPageResponse.ProtoReflect.Descriptor instead.
func (*QueryPageResponse) Descriptor() ([]byte, []int) {
	return file_proto_paginator_proto_rawDescGZIP(), []int{8}
}

func (x *QueryPageResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *QueryPageResponse) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryPageResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *QueryPageResponse) GetTotalPages() uint32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *QueryPageResponse) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *QueryPageResponse) GetHasPrev() bool {
	if x != nil {
		return x.HasPrev
	}
	return false
}

func (x *QueryPageResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

var File_proto_paginator_proto protoreflect.FileDescriptor

const file_proto_paginator_proto_rawDesc = "" +
	"\n" +
	"\x15proto/paginator.proto\x12\x06orm.v1\"\xce\x02\n" +
	"\fQueryOptions\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x16\n" +
	"\x06select\x18\x03 \x03(\tR\x06select\x12%\n" +
	"\x04sort\x18\x04 \x03(\v2\x11.orm.v1.SortFieldR\x04sort\x12+\n" +
	"\x06search\x18\x05 \x01(\v2\x13.orm.v1.SearchQueryR\x06search\x125\n" +
	"\n" +
	"search_and\x18\x06 \x01(\v2\x16.orm.v1.SearchQueryAndR\tsearchAnd\x12(\n" +
	"\afilters\x18\a \x03(\v2\x0e.orm.v1.FilterR\afilters\x12G\n" +
	"\x10in_memory_offset\x18\b \x01(\v2\x1d.orm.v1.InMemoryOffsetOptionsR\x0einMemoryOffset\"5\n" +
	"\tSortField\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\bR\x04desc\"g\n" +
	"\vSearchQuery\x12\x16\n" +
	"\x06fields\x18\x01 \x03(\tR\x06fields\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12&\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x12.orm.v1.SearchModeR\x04mode\"\\\n" +
	"\x15InMemoryOffsetOptions\x12&\n" +
	"\x06cursor\x18\x01 \x01(\v2\x0e.orm.v1.CursorR\x06cursor\x12\x1b\n" +
	"\tmax_limit\x18\x02 \x01(\rR\bmaxLimit\"4\n" +
	"\x06Cursor\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"=\n" +
	"\vSearchField\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\"=\n" +
	"\x0eSearchQueryAnd\x12+\n" +
	"\x06fields\x18\x01 \x03(\v2\x13.orm.v1.SearchFieldR\x06fields\"\x80\x01\n" +
	"\x06Filter\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x122\n" +
	"\boperator\x18\x02 \x01(\x0e2\x16.orm.v1.FilterOperatorR\boperator\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x16\n" +
	"\x06values\x18\x04 \x03(\tR\x06values\"\xcb\x01\n" +
	"\x11QueryPageResponse\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\rR\n" +
	"totalPages\x12\x19\n" +
	"\bhas_next\x18\x05 \x01(\bR\ahasNext\x12\x19\n" +
	"\bhas_prev\x18\x06 \x01(\bR\ahasPrev\x12\x1f\n" +
	"\vnext_cursor\x18\a \x01(\tR\n" +
	"nextCursor*\xb2\x01\n" +
	"\n" +
	"SearchMode\x12\x1b\n" +
	"\x17SEARCH_MODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SEARCH_MODE_CONTAINS\x10\x01\x12\x16\n" +
	"\x12SEARCH_MODE_PREFIX\x10\x02\x12\x19\n" +
	"\x15SEARCH_MODE_FULL_TEXT\x10\x03\x12\x17\n" +
	"\x13SEARCH_MODE_TRIGRAM\x10\x04\x12!\n" +
	"\x1dSEARCH_MODE_FULL_TEXT_TRIGRAM\x10\x05*\xb1\x02\n" +
	"\x0eFilterOperator\x12\x1f\n" +
	"\x1bFILTER_OPERATOR_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15FILTER_OPERATOR_EQUAL\x10\x01\x12\x1d\n" +
	"\x19FILTER_OPERATOR_NOT_EQUAL\x10\x02\x12 \n" +
	"\x1cFILTER_OPERATOR_GREATER_THAN\x10\x03\x12&\n" +
	"\"FILTER_OPERATOR_GREATER_THAN_EQUAL\x10\x04\x12\x1d\n" +
	"\x19FILTER_OPERATOR_LESS_THAN\x10\x05\x12#\n" +
	"\x1fFILTER_OPERATOR_LESS_THAN_EQUAL\x10\x06\x12\x18\n" +
	"\x14FILTER_OPERATOR_LIKE\x10\a\x12\x1c\n" +
	"\x18FILTER_OPERATOR_NOT_LIKE\x10\bB%Z#github.com/siti-nabila/orm/pb;ormpbb\x06proto3"

var (
	file_proto_paginator_proto_rawDescOnce sync.Once
	file_proto_paginator_proto_rawDescData []byte
)

func file_proto_paginator_proto_rawDescGZIP() []byte {
	file_proto_paginator_proto_rawDescOnce.Do(func() {
		file_proto_paginator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_paginator_proto_rawDesc), len(file_proto_paginator_proto_rawDesc)))
	})
	return file_proto_paginator_proto_rawDescData
}

var file_proto_paginator_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_paginator_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_paginator_proto_goTypes = []any{
	(SearchMode)(0),               // 0: orm.v1.SearchMode
	(FilterOperator)(0),           // 1: orm.v1.FilterOperator
	(*QueryOptions)(nil),          // 2: orm.v1.QueryOptions
	(*SortField)(nil),             // 3: orm.v1.SortField
	(*SearchQuery)(nil),           // 4: orm.v1.SearchQuery
	(*InMemoryOffsetOptions)(nil), // 5: orm.v1.InMemoryOffsetOptions
	(*Cursor)(nil),                // 6: orm.v1.Cursor
	(*SearchField)(nil),           // 7: orm.v1.SearchField
	(*SearchQueryAnd)(nil),        // 8: orm.v1.SearchQueryAnd
	(*Filter)(nil),                // 9: orm.v1.Filter
	(*QueryPageResponse)(nil),     // 10: orm.v1.QueryPageResponse
}
var file_proto_paginator_proto_depIdxs = []int32{
	3, // 0: orm.v1.QueryOptions.sort:type_name -> orm.v1.SortField
	4, // 1: orm.v1.QueryOptions.search:type_name -> orm.v1.SearchQuery
	8, // 2: orm.v1.QueryOptions.search_and:type_name -> orm.v1.SearchQueryAnd
	9, // 3: orm.v1.QueryOptions.filters:type_name -> orm.v1.Filter
	5, // 4: orm.v1.QueryOptions.in_memory_offset:type_name -> orm.v1.InMemoryOffsetOptions
	0, // 5: orm.v1.SearchQuery.mode:type_name -> orm.v1.SearchMode
	6, // 6: orm.v1.InMemoryOffsetOptions.cursor:type_name -> orm.v1.Cursor
	7, // 7: orm.v1.SearchQueryAnd.fields:type_name -> orm.v1.SearchField
	1, // 8: orm.v1.Filter.operator:type_name -> orm.v1.FilterOperator
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_proto_paginator_proto_init() }
func file_proto_paginator_proto_init() {
	if File_proto_paginator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_paginator_proto_rawDesc), len(file_proto_paginator_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_paginator_proto_goTypes,
		DependencyIndexes: file_proto_paginator_proto_depIdxs,
		EnumInfos:         file_proto_paginator_proto_enumTypes,
		MessageInfos:      file_proto_paginator_proto_msgTypes,
	}.Build()
	File_proto_paginator_proto = out.File
	file_proto_paginator_proto_goTypes = nil
	file_proto_paginator_proto_depIdxs = nil
}
